allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

onlyBuiltDependencies:
  - sharp

supportedArchitectures:
  os:
    - darwin
  cpu:
    - arm64
